CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, 
			email TEXT NOT NULL, 
			slim_user_id INTEGER NOT NULL);

CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT, 
			name TEXT NOT NULL);

CREATE TABLE tasks(id INTEGER PRIMARY KEY AUTOINCREMENT, 
			user_id INTEGER NOT NULL, 
			task_id INTEGER NOT NULL, 
			name TEXT NOT NULL, 
			completed BOOLEAN DEFAULT FALSE, 
			in_sync BOOLEAN DEFAULT TRUE, 
			deleted BOOLEAN DEFAULT FALSE);

CREATE TABLE entries(id INTEGER PRIMARY KEY AUTOINCREMENT, 
			user_id INTEGER NOT NULL, 
			task_id INTEGER NOT NULL,
			comment TEXT NOT NULL DEFAULT '',
			start_time DATE NOT NULL, 
			end_time DATE);

CREATE TABLE entries_tags (id INTEGER PRIMARY KEY AUTOINCREMENT, 
			entry_id INTEGER NOT NULL, 
			tag_id INTEGER NOT NULL);